# Generated by Django 2.1.7 on 2019-04-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sentence', models.CharField(max_length=300)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
