# Generated by Django 2.1.7 on 2019-04-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190415_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
