# Generated by Django 2.1.7 on 2019-04-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190416_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
