# Generated by Django 2.1.7 on 2019-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190417_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
